### ISSUE TITLE
Update Exams with Current HKN Listings

### ISSUE THREAD

**Issue by kcparashar** [kcparashar/exams#2]
Since one shouldn't rely on one particular source for their wealth of knowledge, to better ensure these are well distributed, porting over the current exams should be done. 

Help would be appreciated!

[HKN Exams](https://hkn.eecs.berkeley.edu/exams/)

**Comment by clayshieh** [comment]
Would the scraper mentioned in #3 not be sufficient/part of the same problem?

**Comment by kcparashar** [comment]
@clayshieh Alas, this was done a few years back and I don't have the script anymore. :(

**Comment by clayshieh** [comment]
should be simple enough. If it hasn't been done by the time I get around to it, I'll write it up.

**Comment by kcparashar** [comment]
Yeah, wasn't too bad I think. But that'd be awesome!

**Comment by clayshieh** [comment]
#4 just in case you missed it.
